# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Secure session configuration
    session:
        handler_id: null
        cookie_secure: auto    # 'true' in prod, 'auto' in dev
        cookie_httponly: true
        cookie_samesite: lax

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
